const visitedCountryCodes = [
  "AE",
  "AT",
  "AU",
  "CH",
  "CN",
  "DK",
  "FR",
  "GB",
  "HK",
  "HR",
  "ID",
  "IS",
  "IT",
  "JP",
  "KR",
  "ME",
  "MY",
  "NL",
  "PH",
  "RS",
  "SG",
  "TH",
  "TW",
  "US",
  "VN",
];

let map = AmCharts.makeChart("map", {
  type: "map",
  theme: "dark",
  projection: "mercator",
  panEventsEnabled: true,
  backgroundColor: "#efefef",
  zoomControl: {
    zoomControlEnabled: true,
  },
  dataProvider: {
    map: "worldHigh",
    getAreasFromMap: true,
    areas: visitedCountryCodes.map(countryCode => Object({
      id: countryCode,
      showAsSelected: true,
    })),
  },
  areasSettings: {
    autoZoom: false,
    color: "#989898",
    colorSolid: "#84ADE9",
    selectedColor: "#84ADE9",
    outlineColor: "#787878",
    rollOverColor: "#9EC2F7",
    rollOverOutlineColor: "#000000",
  },
});
